# Generated by Django 5.0.1 on 2024-09-17 09:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=25)),
                ('sub_series', models.CharField(blank=True, max_length=25)),
                ('n_mols', models.IntegerField(default=0)),
                ('series_bbsar_coverage', models.FloatField(default=0)),
                ('n_bb_tags', models.IntegerField(default=0)),
                ('n_bbs', models.IntegerField(default=0)),
                ('n_A', models.IntegerField(default=0)),
                ('n_B', models.IntegerField(default=0)),
                ('n_C', models.IntegerField(default=0)),
                ('n_D', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'series_name')},
            },
        ),
    ]
