from django.db import models
from projects.models import Project

class Molecule(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    series = models.CharField(max_length=16, default="MCs")
    sub_series = models.CharField(max_length=16, default="MC13")
    mol_smi = models.CharField(max_length=100)
    mol_id = models.CharField(max_length=16)
    mol_flag = models.CharField(max_length=32, null=True)
    A_id = models.CharField(max_length=4, null=True)
    B_id = models.CharField(max_length=4, null=True)
    C_id = models.CharField(max_length=4, null=True)
    D_id = models.CharField(max_length=4, null=True)
    bbs_id = models.CharField(max_length=16, null=True)
    BB_fu = models.FloatField(null=True)
    BBB_Brain = models.FloatField(null=True)
    BBB_Brain_2 = models.FloatField(null=True)
    BBB_Brain_Plasma_ratio = models.FloatField(null=True)
    BBB_Plasma = models.FloatField(null=True)
    BBB_Plasma_2 = models.FloatField(null=True)
    BBB_ratio_BrainPlasma = models.FloatField(null=True)
    CYP_mida = models.FloatField(null=True)
    CYP_shift = models.FloatField(null=True)
    CYP_testo = models.FloatField(null=True)
    CYP2C9_IC50 = models.FloatField(null=True)
    CYP2D6_IC50 = models.FloatField(null=True)
    CYP2C9_screening_IC50 = models.FloatField(null=True)
    CYP2D6_screening_IC50 = models.FloatField(null=True)
    CYP3A4_screening_mida_IC50 = models.FloatField(null=True)
    CYP3A4_screening_testo_IC50 = models.FloatField(null=True)
    DogLM = models.FloatField(null=True)
    DMPK_status = models.CharField(max_length=512, null=True)
    EC50_main = models.FloatField(null=True)
    FLP_EC50 = models.FloatField(null=True)
    FLP_effect = models.FloatField(null=True)
    GSH = models.FloatField(null=True)
    HLM = models.FloatField(null=True)
    hM1R_FLIPR_IC50 = models.FloatField(null=True)
    hM2R_FLIPR_IC50 = models.FloatField(null=True)
    hM3R_FLIPR_IC50 = models.FloatField(null=True)
    hM5R_FLIPR_IC50 = models.FloatField(null=True)
    IP1_effect = models.FloatField(null=True)
    KineticEV_AUC = models.FloatField(null=True)
    KineticEV_Cmax = models.FloatField(null=True)
    KineticIV_AUC = models.FloatField(null=True)
    KineticIV_Clearance = models.FloatField(null=True)
    logD = models.FloatField(null=True)
    MDR1_PappAB = models.FloatField(null=True)
    MDR1_efflux = models.FloatField(null=True)
    min_ratio_hM1R_hM2R = models.FloatField(null=True)
    MouseLM = models.FloatField(null=True)
    OX1_IP1_EC50 = models.FloatField(null=True)
    PPB_fu = models.FloatField(null=True)
    PXR_EC50 = models.FloatField(null=True)
    PXR_Emax = models.FloatField(null=True)
    ratio_hOX1R_hOX2R = models.FloatField(null=True)
    RatLM = models.FloatField(null=True)
    sol_FaSSIF = models.FloatField(null=True)
    sol_pH6 = models.FloatField(null=True)
    Tox_CellTiter_Glo_IC50 = models.FloatField(null=True)
    BPI_calc = models.FloatField(null=True)

    def __str__(self):
        return str(self.pk)
